export const questions = [
  {
    id: "q01",
    question:
      "IT Infrastructure Services (ฝ่ายบริหารโครงสร้างด้านเทคโนโลยีสารสนเทศ)",
    sub_question: [
      {
        id: "01",
        label: "โปรดบอกความต้องการพัฒนาทักษะฝีมือของฝ่ายงานในองค์กรของท่าน",
        type: "radio",
        question:
          "IT Infrastructure Services (ฝ่ายบริหารโครงสร้างด้านเทคโนโลยีสารสนเทศ)",
        choices: ["มาก", "ปานกลาง", "น้อย"],
      },
      {
        id: "01",
        label: "ทักษะฝีมือใดที่พนักงานของท่านมี (เลือกได้มากกว่า 1 ข้อ)",
        question:
          "IT Infrastructure Services (ฝ่ายบริหารโครงสร้างด้านเทคโนโลยีสารสนเทศ)",
        type: "checkbox",
        choices: [
          "การออกแบบและบริหารระบบเครือข่าย (Network Design & Administration)",
          "การบริหารระบบคลาวด์ (AWS, Azure, Google Cloud)",
          "การบริหารจัดการเซิร์ฟเวอร์ (Linux/Windows Server Administration)",
          "การรักษาความปลอดภัยทางไซเบอร์ (Cybersecurity & Firewall Management)",
          "การบริหารและดูแลศูนย์ข้อมูล (Data Center & Virtualization)",
          "การใช้เครื่องมือมอนิเตอร์ระบบ (Nagios, Splunk, Zabbix ฯลฯ)",
          "ไม่ทราบ",
          "อื่นๆ"
        ],
      },
      {
        id: "01",
        label:
          "ทักษะฝีมือด้านใดบ้างที่ท่านต้องการให้พนักงานพัฒนาอย่างต่อเนื่องหรือยังขาดแคลนบุคลากรที่มีทักษะเหล่านี้",
        type: "checkbox",
        question:
          "IT Infrastructure Services (ฝ่ายบริหารโครงสร้างด้านเทคโนโลยีสารสนเทศ)",
        choices: [
          "Cloud Computing & Cloud Security",
          "Cybersecurity & Ethical Hacking",
          "Automation & Infrastructure as Code (IaC)",
          "ไม่ทราบทักษะที่ควรพัฒนา",
          "ไม่ต้องการพัฒนาทักษะสำหรับฝ่ายนี้",
        ],
      },
      {
        id: "01",
        label: "",
        type: "radio",
        question:
          "ท่านคิดว่าทักษะ Soft Skills มีผลต่อประสิทธิภาพการทำงานของพนักงานภายในองค์กรของท่าน มากน้อยเพียงใด?",
        choices: ["มาก", "ปานกลาง", "น้อย"],
      },
      {
        id: "01",
        label: "",
        type: "checkbox",
        question:
          "ทักษะ Soft Skills ใดที่พนักงานของท่านควรได้รับการพัฒนาเพิ่มเติม? (เลือกได้มากกว่า 1 ข้อ)",
        choices: [
          "การสื่อสารและการนำเสนอ (Communication & Presentation)",
          "การทำงานเป็นทีมและการประสานงาน (Teamwork & Collaboration)",
          "การคิดเชิงวิเคราะห์และการแก้ปัญหา (Critical Thinking & Problem Solving)",
          "ความคิดสร้างสรรค์และนวัตกรรม (Creativity & Innovation)",
          "ภาวะผู้นำและการบริหารทีม (Leadership & Management)",
          "การบริหารเวลาและการทำงานอย่างมีประสิทธิภาพ (Time Management & Productivity)",
          "การปรับตัวต่อการเปลี่ยนแปลง (Adaptability & Resilience)",
          "การรับมือกับความเครียดและความกดดัน (Resilience & Stress Management)",
          "การเจรจาต่อรองและแก้ไขความขัดแย้ง (Negotiation & Conflict Resolution)",
          "อื่นๆ",
        ],
      },
      {
        id: "01",
        label: "",
        type: "checkbox",
        question: "ท่านสะดวกฝึกอบรม ช่วงเวลาใด ",
        choices: ["จันทร์ - ศุกร์", "เสาร์ - อาทิตย์", "ทุกช่วงเวลา"],
      },
      {
        id: "01",
        label: "",
        type: "radio",
        question: "ท่านสะดวกฝึกอบรม ช่วงเวลาใด ",
        choices: [
          "ณ สถาบันพัฒนาฝีมือแรงงาน",
          "ณ สถานประกอบการ/บริษัทของท่าน",
          "Online Training",
        ],
      },
      {
        id: "01",
        label: "",
        type: "checkbox",
        question: "ท่านต้องการให้หลักสูตรฝึกอบรมมีการประเมินผลอย่างไร?",
        choices: [
          "การทดสอบหลังการฝึกอบรม",
          "การประเมินผลจากผู้เข้าร่วม",
          "การประเมินผลจากผู้สอน",
          "ไม่มีการประเมินผล",
        ],
      },
      {
        id: "01",
        label: "",
        type: "radio",
        question: "ท่านต้องการให้หลักสูตรมีใบรับรองหรือประกาศนียบัตรหรือไม่?",
        choices: ["จำเป็น", "ไม่จำเป็น"],
      },
    ],
  },
  {
    id: "q02",
    question: "Software Enterprise Services (ฝ่ายบริการซอฟต์แวร์ธุรกิจองค์กร)",

    sub_question: [
      {
        id: "02",
        label: "โปรดบอกความต้องการพัฒนาทักษะฝีมือของฝ่ายงานในองค์กรของท่าน",
        type: "radio",
        question:
          "Software Enterprise Services (ฝ่ายบริการซอฟต์แวร์ธุรกิจองค์กร)",
        choices: ["มาก", "ปานกลาง", "น้อย"],
      },
      {
        id: "02",
        label: "ทักษะฝีมือใดที่พนักงานของท่านมี (เลือกได้มากกว่า 1 ข้อ)",
        type: "checkbox",
        question:
          "Software Enterprise Services (ฝ่ายบริการซอฟต์แวร์ธุรกิจองค์กร)",
        choices: [
          "ความรู้ด้าน ERP (SAP, Oracle, Microsoft Dynamics ฯลฯ)",
          "การพัฒนาและปรับแต่งซอฟต์แวร์ธุรกิจ (Customization & Integration)",
          "การบริหารฐานข้อมูล (SQL, NoSQL)",
          "ความเข้าใจในระบบ Business Intelligence (Power BI, Tableau)",
          "การใช้ API และ Middleware เพื่อเชื่อมโยงระบบ",
          "ไม่ทราบ",
          "อื่นๆ"
        ],
      },
      {
        id: "02",
        label:
          "ทักษะฝีมือด้านใดบ้างที่ท่านต้องการให้พนักงานพัฒนาอย่างต่อเนื่องหรือยังขาดแคลนบุคลากรที่มีทักษะเหล่านี้",
        type: "checkbox",
        question:
          "Software Enterprise Services (ฝ่ายบริการซอฟต์แวร์ธุรกิจองค์กร)",
        choices: [
          "Enterprise Resource Planning (ERP) Implementation",
          "Data Analytics & Business Intelligence",
          "AI & Process Automation",
          "ไม่ทราบทักษะที่ควรพัฒนา",
          "ไม่ต้องการพัฒนาทักษะสำหรับฝ่ายนี้",
        ],
      },
      {
        id: "02",
        label: "",
        type: "radio",
        question:
          "ท่านคิดว่าทักษะ Soft Skills มีผลต่อประสิทธิภาพการทำงานของพนักงานภายในองค์กรของท่าน มากน้อยเพียงใด?",
        choices: ["มาก", "ปานกลาง", "น้อย"],
      },
      {
        id: "02",
        label: "",
        type: "checkbox",
        question:
          "ทักษะ Soft Skills ใดที่พนักงานของท่านควรได้รับการพัฒนาเพิ่มเติม? (เลือกได้มากกว่า 1 ข้อ)",
        choices: [
          "การสื่อสารและการนำเสนอ (Communication & Presentation)",
          "การทำงานเป็นทีมและการประสานงาน (Teamwork & Collaboration)",
          "การคิดเชิงวิเคราะห์และการแก้ปัญหา (Critical Thinking & Problem Solving)",
          "ความคิดสร้างสรรค์และนวัตกรรม (Creativity & Innovation)",
          "ภาวะผู้นำและการบริหารทีม (Leadership & Management)",
          "การบริหารเวลาและการทำงานอย่างมีประสิทธิภาพ (Time Management & Productivity)",
          "การปรับตัวต่อการเปลี่ยนแปลง (Adaptability & Resilience)",
          "การรับมือกับความเครียดและความกดดัน Resilience & Stress Management",
          "การเจรจาต่อรองและแก้ไขความขัดแย้ง Negotiation & Conflict Resolution",
          "อื่นๆ",
        ],
      },
      {
        id: "02",
        label: "",
        type: "checkbox",
        question: "ท่านสะดวกฝึกอบรม ช่วงเวลาใด ",
        choices: ["จันทร์ - ศุกร์", "เสาร์ - อาทิตย์", "ทุกช่วงเวลา"],
      },
      {
        id: "02",
        label: "",
        type: "radio",
        question: "ท่านสะดวกฝึกอบรม ช่วงเวลาใด ",
        choices: [
          "ณ สถาบันพัฒนาฝีมือแรงงาน",
          "ณ สถานประกอบการ/บริษัทของท่าน",
          "Online Training",
        ],
      },
      {
        id: "02",
        label: "",
        type: "checkbox",
        question: "ท่านต้องการให้หลักสูตรฝึกอบรมมีการประเมินผลอย่างไร?",
        choices: [
          "การทดสอบหลังการฝึกอบรม",
          "การประเมินผลจากผู้เข้าร่วม",
          "การประเมินผลจากผู้สอน",
          "ไม่มีการประเมินผล",
        ],
      },
      {
        id: "02",
        label: "",
        type: "radio",
        question: "ท่านต้องการให้หลักสูตรมีใบรับรองหรือประกาศนียบัตรหรือไม่?",
        choices: ["จำเป็น", "ไม่จำเป็น"],
      },
    ],
  },
  {
    id: "q03",
    question: "IT Services (ฝ่ายบริการเทคโนโลยีสารสนเทศ)",

    sub_question: [
      {
        id: "03",
        label: "โปรดบอกความต้องการพัฒนาทักษะฝีมือของฝ่ายงานในองค์กรของท่าน",
        type: "radio",
        question: "IT Services (ฝ่ายบริการเทคโนโลยีสารสนเทศ)",
        choices: ["มาก", "ปานกลาง", "น้อย"],
      },
      {
        id: "03",
        label: "ทักษะฝีมือใดที่พนักงานของท่านมี (เลือกได้มากกว่า 1 ข้อ)",
        type: "radio",
        question: "IT Services (ฝ่ายบริการเทคโนโลยีสารสนเทศ)",
        choices: [
          "การดูแลและสนับสนุนผู้ใช้ (IT Support & Helpdesk)",
          "การติดตั้งและซ่อมแซมอุปกรณ์ IT (Hardware & Software Troubleshooting)",
          "การบริหารสิทธิ์การเข้าถึงระบบ (Access Control & Active Directory)",
          "การจัดการความปลอดภัยข้อมูลเบื้องต้น (Endpoint Security)",
          "ไม่ทราบ",
          "อื่นๆ"
        ],
      },
      {
        id: "03",
        label:
          "ทักษะฝีมือด้านใดบ้างที่ท่านต้องการให้พนักงานพัฒนาอย่างต่อเนื่องหรือยังขาดแคลนบุคลากรที่มีทักษะเหล่านี้",
        type: "checkbox",
        question: "IT Services (ฝ่ายบริการเทคโนโลยีสารสนเทศ)",
        choices: [
          "IT Support & Helpdesk with AI Integration",
          "Endpoint Security & Zero Trust Architecture",
          "ITIL & IT Service Management",
          "ไม่ทราบทักษะที่ควรพัฒนา",
          "ไม่ต้องการพัฒนาทักษะสำหรับฝ่ายนี้",
        ],
      },
      {
        id: "03",
        label: "",
        type: "radio",
        question:
          "ท่านคิดว่าทักษะ Soft Skills มีผลต่อประสิทธิภาพการทำงานของพนักงานภายในองค์กรของท่าน มากน้อยเพียงใด?",
        choices: ["มาก", "ปานกลาง", "น้อย"],
      },
      {
        id: "03",
        label: "",
        type: "checkbox",
        question:
          "ทักษะ Soft Skills ใดที่พนักงานของท่านควรได้รับการพัฒนาเพิ่มเติม? (เลือกได้มากกว่า 1 ข้อ)",
        choices: [
          "การสื่อสารและการนำเสนอ (Communication & Presentation)",
          "การทำงานเป็นทีมและการประสานงาน (Teamwork & Collaboration)",
          "การคิดเชิงวิเคราะห์และการแก้ปัญหา (Critical Thinking & Problem Solving)",
          "ความคิดสร้างสรรค์และนวัตกรรม (Creativity & Innovation)",
          "ภาวะผู้นำและการบริหารทีม (Leadership & Management)",
          "การบริหารเวลาและการทำงานอย่างมีประสิทธิภาพ (Time Management & Productivity)",
          "การปรับตัวต่อการเปลี่ยนแปลง (Adaptability & Resilience)",
          "การรับมือกับความเครียดและความกดดัน Resilience & Stress Management",
          "การเจรจาต่อรองและแก้ไขความขัดแย้ง Negotiation & Conflict Resolution",
          "อื่นๆ",
        ],
      },
      {
        id: "03",
        label: "",
        type: "checkbox",
        question: "ท่านสะดวกฝึกอบรม ช่วงเวลาใด ",
        choices: ["จันทร์ - ศุกร์", "เสาร์ - อาทิตย์", "ทุกช่วงเวลา"],
      },
      {
        id: "03",
        label: "",
        type: "radio",
        question: "ท่านสะดวกฝึกอบรม ช่วงเวลาใด ",
        choices: [
          "ณ สถาบันพัฒนาฝีมือแรงงาน",
          "ณ สถานประกอบการ/บริษัทของท่าน",
          "Online Training",
        ],
      },
      {
        id: "03",
        label: "",
        type: "checkbox",
        question: "ท่านต้องการให้หลักสูตรฝึกอบรมมีการประเมินผลอย่างไร?",
        choices: [
          "การทดสอบหลังการฝึกอบรม",
          "การประเมินผลจากผู้เข้าร่วม",
          "การประเมินผลจากผู้สอน",
          "ไม่มีการประเมินผล",
        ],
      },
      {
        id: "03",
        label: "",
        type: "radio",
        question: "ท่านต้องการให้หลักสูตรมีใบรับรองหรือประกาศนียบัตรหรือไม่?",
        choices: ["จำเป็น", "ไม่จำเป็น"],
      },
    ],
  },
  {
    id: "q04",
    question: "Solutions Development (ฝ่ายพัฒนาดิจิทัลโซลูชั่นส์)",
    sub_question: [
      {
        id: "04",
        label: "โปรดบอกความต้องการพัฒนาทักษะฝีมือของฝ่ายงานในองค์กรของท่าน",
        type: "radio",
        question: "Solutions Development (ฝ่ายพัฒนาดิจิทัลโซลูชั่นส์)",
        choices: ["มาก", "ปานกลาง", "น้อย"],
      },
      {
        id: "04",
        label: "ทักษะฝีมือใดที่พนักงานของท่านมี (เลือกได้มากกว่า 1 ข้อ)",
        type: "checkbox",
        question: "Solutions Development (ฝ่ายพัฒนาดิจิทัลโซลูชั่นส์)",
        choices: [
          "การพัฒนาเว็บและแอปพลิเคชัน (Frontend & Backend Development)",
          "ความรู้ด้าน API และ Web Services (REST, GraphQL)",
          "การพัฒนา AI & Machine Learning",
          "การใช้เครื่องมือ DevOps (Docker, Kubernetes, CI/CD)",
          "การออกแบบสถาปัตยกรรมซอฟต์แวร์",
          "ไม่ทราบ",
          "อื่นๆ"
        ],
      },
      {
        id: "04",
        label:
          "ทักษะฝีมือด้านใดบ้างที่ท่านต้องการให้พนักงานพัฒนาอย่างต่อเนื่องหรือยังขาดแคลนบุคลากรที่มีทักษะเหล่านี้",
        type: "checkbox",
        question: "Solutions Development (ฝ่ายพัฒนาดิจิทัลโซลูชั่นส์)",
        choices: [
          "Full-Stack Development",
          "DevOps & CI/CD",
          "AI & Machine Learning Development",
          "ไม่ทราบทักษะที่ควรพัฒนา",
          "ไม่ต้องการพัฒนาทักษะสำหรับฝ่ายนี้",
        ],
      },
      {
        id: "04",
        label: "",
        type: "radio",
        question:
          "ท่านคิดว่าทักษะ Soft Skills มีผลต่อประสิทธิภาพการทำงานของพนักงานภายในองค์กรของท่าน มากน้อยเพียงใด?",
        choices: ["มาก", "ปานกลาง", "น้อย"],
      },
      {
        id: "04",
        label: "",
        type: "checkbox",
        question:
          "ทักษะ Soft Skills ใดที่พนักงานของท่านควรได้รับการพัฒนาเพิ่มเติม? (เลือกได้มากกว่า 1 ข้อ)",
        choices: [
          "การสื่อสารและการนำเสนอ (Communication & Presentation)",
          "การทำงานเป็นทีมและการประสานงาน (Teamwork & Collaboration)",
          "การคิดเชิงวิเคราะห์และการแก้ปัญหา (Critical Thinking & Problem Solving)",
          "ความคิดสร้างสรรค์และนวัตกรรม (Creativity & Innovation)",
          "ภาวะผู้นำและการบริหารทีม (Leadership & Management)",
          "การบริหารเวลาและการทำงานอย่างมีประสิทธิภาพ (Time Management & Productivity)",
          "การปรับตัวต่อการเปลี่ยนแปลง (Adaptability & Resilience)",
          "การรับมือกับความเครียดและความกดดัน Resilience & Stress Management",
          "การเจรจาต่อรองและแก้ไขความขัดแย้ง Negotiation & Conflict Resolution",
          "อื่นๆ",
        ],
      },
      {
        id: "04",
        label: "",
        type: "checkbox",
        question: "ท่านสะดวกฝึกอบรม ช่วงเวลาใด ",
        choices: ["จันทร์ - ศุกร์", "เสาร์ - อาทิตย์", "ทุกช่วงเวลา"],
      },
      {
        id: "04",
        label: "",
        type: "radio",
        question: "ท่านสะดวกฝึกอบรม ช่วงเวลาใด ",
        choices: [
          "ณ สถาบันพัฒนาฝีมือแรงงาน",
          "ณ สถานประกอบการ/บริษัทของท่าน",
          "Online Training",
        ],
      },
      {
        id: "04",
        label: "",
        type: "checkbox",
        question: "ท่านต้องการให้หลักสูตรฝึกอบรมมีการประเมินผลอย่างไร?",
        choices: [
          "การทดสอบหลังการฝึกอบรม",
          "การประเมินผลจากผู้เข้าร่วม",
          "การประเมินผลจากผู้สอน",
          "ไม่มีการประเมินผล",
        ],
      },
      {
        id: "04",
        label: "",
        type: "radio",
        question: "ท่านต้องการให้หลักสูตรมีใบรับรองหรือประกาศนียบัตรหรือไม่?",
        choices: ["จำเป็น", "ไม่จำเป็น"],
      },
    ],
  },
  {
    id: "q05",
    question: "Accounting & Finance (งานบัญชีและการเงิน)",
    sub_question: [
      {
        id: "05",
        label: "โปรดบอกความต้องการพัฒนาทักษะฝีมือของฝ่ายงานในองค์กรของท่าน",
        type: "radio",
        question: "Accounting & Finance (งานบัญชีและการเงิน)",
        choices: ["มาก", "ปานกลาง", "น้อย"],
      },
      {
        id: "05",
        label: "ทักษะฝีมือใดที่พนักงานของท่านมี (เลือกได้มากกว่า 1 ข้อ)",
        type: "checkbox",
        question: "Accounting & Finance (งานบัญชีและการเงิน)",
        choices: [
          "การใช้โปรแกรมบัญชี (SAP, QuickBooks, Oracle Finance)",
          "การวิเคราะห์และบริหารงบประมาณ",
          "การคำนวณภาษีและงบการเงิน",
          "ความรู้ด้านกฎหมายและมาตรฐานบัญชี",
          "ไม่ทราบ",
        ],
      },
      {
        id: "05",
        label:
          "ทักษะฝีมือด้านใดบ้างที่ท่านต้องการให้พนักงานพัฒนาอย่างต่อเนื่องหรือยังขาดแคลนบุคลากรที่มีทักษะเหล่านี้",
        type: "checkbox",
        question: "Accounting & Finance (งานบัญชีและการเงิน)",
        choices: [
          "Data Analytics for Finance",
          "Blockchain & Digital Payment Systems",
          "Regulatory Compliance & International Taxation",
          "ไม่ทราบทักษะที่ควรพัฒนา",
          "ไม่ต้องการพัฒนาทักษะสำหรับฝ่ายนี้",
        ],
      },
      {
        id: "05",
        label: "",
        type: "radio",
        question:
          "ท่านคิดว่าทักษะ Soft Skills มีผลต่อประสิทธิภาพการทำงานของพนักงานภายในองค์กรของท่าน มากน้อยเพียงใด?",
        choices: ["มาก", "ปานกลาง", "น้อย"],
      },
      {
        id: "05",
        label: "",
        type: "checkbox",
        question:
          "ทักษะ Soft Skills ใดที่พนักงานของท่านควรได้รับการพัฒนาเพิ่มเติม? (เลือกได้มากกว่า 1 ข้อ)",
        choices: [
          "การสื่อสารและการนำเสนอ (Communication & Presentation)",
          "การทำงานเป็นทีมและการประสานงาน (Teamwork & Collaboration)",
          "การคิดเชิงวิเคราะห์และการแก้ปัญหา (Critical Thinking & Problem Solving)",
          "ความคิดสร้างสรรค์และนวัตกรรม (Creativity & Innovation)",
          "ภาวะผู้นำและการบริหารทีม (Leadership & Management)",
          "การบริหารเวลาและการทำงานอย่างมีประสิทธิภาพ (Time Management & Productivity)",
          "การปรับตัวต่อการเปลี่ยนแปลง (Adaptability & Resilience)",
          "การรับมือกับความเครียดและความกดดัน Resilience & Stress Management",
          "การเจรจาต่อรองและแก้ไขความขัดแย้ง Negotiation & Conflict Resolution",
          "อื่นๆ",
        ],
      },
      {
        id: "05",
        label: "",
        type: "checkbox",
        question: "ท่านสะดวกฝึกอบรม ช่วงเวลาใด ",
        choices: ["จันทร์ - ศุกร์", "เสาร์ - อาทิตย์", "ทุกช่วงเวลา"],
      },
      {
        id: "05",
        label: "",
        type: "radio",
        question: "ท่านสะดวกฝึกอบรม ช่วงเวลาใด ",
        choices: [
          "ณ สถาบันพัฒนาฝีมือแรงงาน",
          "ณ สถานประกอบการ/บริษัทของท่าน",
          "Online Training",
        ],
      },
      {
        id: "05",
        label: "",
        type: "checkbox",
        question: "ท่านต้องการให้หลักสูตรฝึกอบรมมีการประเมินผลอย่างไร?",
        choices: [
          "การทดสอบหลังการฝึกอบรม",
          "การประเมินผลจากผู้เข้าร่วม",
          "การประเมินผลจากผู้สอน",
          "ไม่มีการประเมินผล",
        ],
      },
      {
        id: "05",
        label: "",
        type: "radio",
        question: "ท่านต้องการให้หลักสูตรมีใบรับรองหรือประกาศนียบัตรหรือไม่?",
        choices: ["จำเป็น", "ไม่จำเป็น"],
      },
    ],
  },
  {
    id: "q06",
    question: "Human Resource (ฝ่ายทรัพยากรบุคคล)",
    sub_question: [
      {
        id: "06",
        label: "โปรดบอกความต้องการพัฒนาทักษะฝีมือของฝ่ายงานในองค์กรของท่าน",
        type: "radio",
        question: "Human Resource (ฝ่ายทรัพยากรบุคคล)",
        choices: ["มาก", "ปานกลาง", "น้อย"],
      },
      {
        id: "06",
        label: "ทักษะฝีมือใดที่พนักงานของท่านมี (เลือกได้มากกว่า 1 ข้อ)",
        type: "checkbox",
        question: "Human Resource (ฝ่ายทรัพยากรบุคคล)",
        choices: [
          "การบริหารทรัพยากรบุคคล (HR Management)",
          "การใช้ HR Software (SAP HR, Workday, BambooHR)",
          "การคำนวณเงินเดือนและสวัสดิการ",
          "การจัดการด้านแรงงานสัมพันธ์และกฎหมายแรงงาน",
          "ไม่ทราบ",
        ],
      },
      {
        id: "06",
        label:
          "ทักษะฝีมือด้านใดบ้างที่ท่านต้องการให้พนักงานพัฒนาอย่างต่อเนื่องหรือยังขาดแคลนบุคลากรที่มีทักษะเหล่านี้",
        type: "checkbox",
        question: "Human Resource (ฝ่ายทรัพยากรบุคคล)",
        choices: [
          "HR Analytics & People Data Science",
          "HR Technology (HRIS, Workday, SAP SuccessFactors)",
          "Employer Branding & Employee Experience Design",
          "ไม่ทราบทักษะที่ควรพัฒนา",
          "ไม่ต้องการพัฒนาทักษะสำหรับฝ่ายนี้",
        ],
      },{
        id: "06",
        label: "",
        type: "radio",
        question:
          "ท่านคิดว่าทักษะ Soft Skills มีผลต่อประสิทธิภาพการทำงานของพนักงานภายในองค์กรของท่าน มากน้อยเพียงใด?",
        choices: ["มาก", "ปานกลาง", "น้อย"],
      },
      {
        id: "06",
        label: "",
        type: "checkbox",
        question:
          "ทักษะ Soft Skills ใดที่พนักงานของท่านควรได้รับการพัฒนาเพิ่มเติม? (เลือกได้มากกว่า 1 ข้อ)",
        choices: [
          "การสื่อสารและการนำเสนอ (Communication & Presentation)",
          "การทำงานเป็นทีมและการประสานงาน (Teamwork & Collaboration)",
          "การคิดเชิงวิเคราะห์และการแก้ปัญหา (Critical Thinking & Problem Solving)",
          "ความคิดสร้างสรรค์และนวัตกรรม (Creativity & Innovation)",
          "ภาวะผู้นำและการบริหารทีม (Leadership & Management)",
          "การบริหารเวลาและการทำงานอย่างมีประสิทธิภาพ (Time Management & Productivity)",
          "การปรับตัวต่อการเปลี่ยนแปลง (Adaptability & Resilience)",
          "การรับมือกับความเครียดและความกดดัน Resilience & Stress Management",
          "การเจรจาต่อรองและแก้ไขความขัดแย้ง Negotiation & Conflict Resolution",
          "อื่นๆ",
        ],
      },
      {
        id: "06",
        label: "",
        type: "checkbox",
        question: "ท่านสะดวกฝึกอบรม ช่วงเวลาใด ",
        choices: ["จันทร์ - ศุกร์", "เสาร์ - อาทิตย์", "ทุกช่วงเวลา"],
      },
      {
        id: "06",
        label: "",
        type: "radio",
        question: "ท่านสะดวกฝึกอบรม ช่วงเวลาใด ",
        choices: [
          "ณ สถาบันพัฒนาฝีมือแรงงาน",
          "ณ สถานประกอบการ/บริษัทของท่าน",
          "Online Training",
        ],
      },
      {
        id: "06",
        label: "",
        type: "checkbox",
        question: "ท่านต้องการให้หลักสูตรฝึกอบรมมีการประเมินผลอย่างไร?",
        choices: [
          "การทดสอบหลังการฝึกอบรม",
          "การประเมินผลจากผู้เข้าร่วม",
          "การประเมินผลจากผู้สอน",
          "ไม่มีการประเมินผล",
        ],
      },
      {
        id: "06",
        label: "",
        type: "radio",
        question: "ท่านต้องการให้หลักสูตรมีใบรับรองหรือประกาศนียบัตรหรือไม่?",
        choices: ["จำเป็น", "ไม่จำเป็น"],
      },
    ],
  },
  {
    id: "q07",
    question: "Administration (ฝ่ายธุรการ)",
    sub_question: [
      {
        id: "07",
        label: "โปรดบอกความต้องการพัฒนาทักษะฝีมือของฝ่ายงานในองค์กรของท่าน",
        type: "radio",
        question: "Administration (ฝ่ายธุรการ)",
        choices: ["มาก", "ปานกลาง", "น้อย"],
      },
      {
        id: "07",
        label: "ทักษะฝีมือใดที่พนักงานของท่านมี (เลือกได้มากกว่า 1 ข้อ)",
        type: "checkbox",
        question: "Administration (ฝ่ายธุรการ)",
        choices: [
          "การบริหารงานเอกสารและข้อมูล (Document & Records Management)",
          "การใช้โปรแกรมสำนักงาน (Microsoft Office, Google Workspace)",
          "การจัดการระบบอำนวยความสะดวกในองค์กร",
          "ไม่ทราบ",
        ],
      },
      {
        id: "07",
        label:
          "ทักษะฝีมือด้านใดบ้างที่ท่านต้องการให้พนักงานพัฒนาอย่างต่อเนื่องหรือยังขาดแคลนบุคลากรที่มีทักษะเหล่านี้",
        type: "checkbox",
        question: "Administration (ฝ่ายธุรการ)",
        choices: [
          "Digital Office Management",
          "E-Document & Workflow Automation",
          "Project Coordination Tools",
          "ไม่ทราบทักษะที่ควรพัฒนา",
          "ไม่ต้องการพัฒนาทักษะสำหรับฝ่ายนี้",
        ],
      },
      {
        id: "07",
        label: "",
        type: "radio",
        question:
          "ท่านคิดว่าทักษะ Soft Skills มีผลต่อประสิทธิภาพการทำงานของพนักงานภายในองค์กรของท่าน มากน้อยเพียงใด?",
        choices: ["มาก", "ปานกลาง", "น้อย"],
      },
      {
        id: "07",
        label: "",
        type: "checkbox",
        question:
          "ทักษะ Soft Skills ใดที่พนักงานของท่านควรได้รับการพัฒนาเพิ่มเติม? (เลือกได้มากกว่า 1 ข้อ)",
        choices: [
          "การสื่อสารและการนำเสนอ (Communication & Presentation)",
          "การทำงานเป็นทีมและการประสานงาน (Teamwork & Collaboration)",
          "การคิดเชิงวิเคราะห์และการแก้ปัญหา (Critical Thinking & Problem Solving)",
          "ความคิดสร้างสรรค์และนวัตกรรม (Creativity & Innovation)",
          "ภาวะผู้นำและการบริหารทีม (Leadership & Management)",
          "การบริหารเวลาและการทำงานอย่างมีประสิทธิภาพ (Time Management & Productivity)",
          "การปรับตัวต่อการเปลี่ยนแปลง (Adaptability & Resilience)",
          "การรับมือกับความเครียดและความกดดัน Resilience & Stress Management",
          "การเจรจาต่อรองและแก้ไขความขัดแย้ง Negotiation & Conflict Resolution",
          "อื่นๆ",
        ],
      },
      {
        id: "07",
        label: "",
        type: "checkbox",
        question: "ท่านสะดวกฝึกอบรม ช่วงเวลาใด ",
        choices: ["จันทร์ - ศุกร์", "เสาร์ - อาทิตย์", "ทุกช่วงเวลา"],
      },
      {
        id: "07",
        label: "",
        type: "radio",
        question: "ท่านสะดวกฝึกอบรม ช่วงเวลาใด ",
        choices: [
          "ณ สถาบันพัฒนาฝีมือแรงงาน",
          "ณ สถานประกอบการ/บริษัทของท่าน",
          "Online Training",
        ],
      },
      {
        id: "07",
        label: "",
        type: "checkbox",
        question: "ท่านต้องการให้หลักสูตรฝึกอบรมมีการประเมินผลอย่างไร?",
        choices: [
          "การทดสอบหลังการฝึกอบรม",
          "การประเมินผลจากผู้เข้าร่วม",
          "การประเมินผลจากผู้สอน",
          "ไม่มีการประเมินผล",
        ],
      },
      {
        id: "07",
        label: "",
        type: "radio",
        question: "ท่านต้องการให้หลักสูตรมีใบรับรองหรือประกาศนียบัตรหรือไม่?",
        choices: ["จำเป็น", "ไม่จำเป็น"],
      },
    ],
  },
  {
    id: "q08",
    question: "Procurement (ฝ่ายจัดซื้อ)",
    sub_question: [
      {
        id: "08",
        label: "โปรดบอกความต้องการพัฒนาทักษะฝีมือของฝ่ายงานในองค์กรของท่าน",
        type: "radio",
        question: "Procurement (ฝ่ายจัดซื้อ)",
        choices: ["มาก", "ปานกลาง", "น้อย"],
      },
      {
        id: "08",
        label: "ทักษะฝีมือใดที่พนักงานของท่านมี (เลือกได้มากกว่า 1 ข้อ)",
        type: "checkbox",
        question: "Procurement (ฝ่ายจัดซื้อ)",
        choices: [
          "การบริหารจัดซื้อและซัพพลายเชน (Procurement & Supply Chain Management)",
          "การเจรจาต่อรองและการทำสัญญา",
          "ความเข้าใจเกี่ยวกับต้นทุนและงบประมาณ",
          "ไม่ทราบ",
        ],
      },
      {
        id: "08",
        label:
          "ทักษะฝีมือด้านใดบ้างที่ท่านต้องการให้พนักงานพัฒนาอย่างต่อเนื่องหรือยังขาดแคลนบุคลากรที่มีทักษะเหล่านี้",
        type: "checkbox",
        question: "Procurement (ฝ่ายจัดซื้อ)",
        choices: [
          "E-Procurement & Supply Chain Analytics",
          "Sustainable Procurement & ESG Compliance",
          "Data-Driven Decision Making in Procurement",
          "ไม่ทราบทักษะที่ควรพัฒนา",
          "ไม่ต้องการพัฒนาทักษะสำหรับฝ่ายนี้",
        ],
      },
      {
        id: "08",
        label: "",
        type: "radio",
        question:
          "ท่านคิดว่าทักษะ Soft Skills มีผลต่อประสิทธิภาพการทำงานของพนักงานภายในองค์กรของท่าน มากน้อยเพียงใด?",
        choices: ["มาก", "ปานกลาง", "น้อย"],
      },
      {
        id: "08",
        label: "",
        type: "checkbox",
        question:
          "ทักษะ Soft Skills ใดที่พนักงานของท่านควรได้รับการพัฒนาเพิ่มเติม? (เลือกได้มากกว่า 1 ข้อ)",
        choices: [
          "การสื่อสารและการนำเสนอ (Communication & Presentation)",
          "การทำงานเป็นทีมและการประสานงาน (Teamwork & Collaboration)",
          "การคิดเชิงวิเคราะห์และการแก้ปัญหา (Critical Thinking & Problem Solving)",
          "ความคิดสร้างสรรค์และนวัตกรรม (Creativity & Innovation)",
          "ภาวะผู้นำและการบริหารทีม (Leadership & Management)",
          "การบริหารเวลาและการทำงานอย่างมีประสิทธิภาพ (Time Management & Productivity)",
          "การปรับตัวต่อการเปลี่ยนแปลง (Adaptability & Resilience)",
          "การรับมือกับความเครียดและความกดดัน Resilience & Stress Management",
          "การเจรจาต่อรองและแก้ไขความขัดแย้ง Negotiation & Conflict Resolution",
          "อื่นๆ",
        ],
      },
      {
        id: "08",
        label: "",
        type: "checkbox",
        question: "ท่านสะดวกฝึกอบรม ช่วงเวลาใด ",
        choices: ["จันทร์ - ศุกร์", "เสาร์ - อาทิตย์", "ทุกช่วงเวลา"],
      },
      {
        id: "08",
        label: "",
        type: "radio",
        question: "ท่านสะดวกฝึกอบรม ช่วงเวลาใด ",
        choices: [
          "ณ สถาบันพัฒนาฝีมือแรงงาน",
          "ณ สถานประกอบการ/บริษัทของท่าน",
          "Online Training",
        ],
      },
      {
        id: "08",
        label: "",
        type: "checkbox",
        question: "ท่านต้องการให้หลักสูตรฝึกอบรมมีการประเมินผลอย่างไร?",
        choices: [
          "การทดสอบหลังการฝึกอบรม",
          "การประเมินผลจากผู้เข้าร่วม",
          "การประเมินผลจากผู้สอน",
          "ไม่มีการประเมินผล",
        ],
      },
      {
        id: "08",
        label: "",
        type: "radio",
        question: "ท่านต้องการให้หลักสูตรมีใบรับรองหรือประกาศนียบัตรหรือไม่?",
        choices: ["จำเป็น", "ไม่จำเป็น"],
      },
    ],
  },
  {
    id: "q09",
    question: "Project Management (ฝ่ายบริหารงานโครงการ)",
    sub_question: [
      {
        id: "09",
        label: "โปรดบอกความต้องการพัฒนาทักษะฝีมือของฝ่ายงานในองค์กรของท่าน",
        type: "radio",
        question: "Project Management (ฝ่ายบริหารงานโครงการ)",
        choices: ["มาก", "ปานกลาง", "น้อย"],
      },
      {
        id: "09",
        label: "ทักษะฝีมือใดที่พนักงานของท่านมี (เลือกได้มากกว่า 1 ข้อ)",
        type: "checkbox",
        question: "Project Management (ฝ่ายบริหารงานโครงการ)",
        choices: [
          "การใช้เครื่องมือบริหารโครงการ (JIRA, Trello, Asana)",
          "ความเข้าใจเกี่ยวกับ Agile & Scrum หรือ Waterfall",
          "การบริหารทรัพยากรและงบประมาณโครงการ",
          "การวิเคราะห์และบริหารความเสี่ยง",
          "ไม่ทราบ",
        ],
      },
      {
        id: "09",
        label:
          "ทักษะฝีมือด้านใดบ้างที่ท่านต้องการให้พนักงานพัฒนาอย่างต่อเนื่องหรือยังขาดแคลนบุคลากรที่มีทักษะเหล่านี้",
        type: "checkbox",
        question: "Project Management (ฝ่ายบริหารงานโครงการ)",
        choices: [
          "Agile & Scrum Mastery",
          "Risk Management & Change Management",
          "Project Financial Management",
          "ไม่ทราบทักษะที่ควรพัฒนา",
          "ไม่ต้องการพัฒนาทักษะสำหรับฝ่ายนี้",
        ],
      },
      {
        id: "09",
        label: "",
        type: "radio",
        question:
          "ท่านคิดว่าทักษะ Soft Skills มีผลต่อประสิทธิภาพการทำงานของพนักงานภายในองค์กรของท่าน มากน้อยเพียงใด?",
        choices: ["มาก", "ปานกลาง", "น้อย"],
      },
      {
        id: "09",
        label: "",
        type: "checkbox",
        question:
          "ทักษะ Soft Skills ใดที่พนักงานของท่านควรได้รับการพัฒนาเพิ่มเติม? (เลือกได้มากกว่า 1 ข้อ)",
        choices: [
          "การสื่อสารและการนำเสนอ (Communication & Presentation)",
          "การทำงานเป็นทีมและการประสานงาน (Teamwork & Collaboration)",
          "การคิดเชิงวิเคราะห์และการแก้ปัญหา (Critical Thinking & Problem Solving)",
          "ความคิดสร้างสรรค์และนวัตกรรม (Creativity & Innovation)",
          "ภาวะผู้นำและการบริหารทีม (Leadership & Management)",
          "การบริหารเวลาและการทำงานอย่างมีประสิทธิภาพ (Time Management & Productivity)",
          "การปรับตัวต่อการเปลี่ยนแปลง (Adaptability & Resilience)",
          "การรับมือกับความเครียดและความกดดัน Resilience & Stress Management",
          "การเจรจาต่อรองและแก้ไขความขัดแย้ง Negotiation & Conflict Resolution",
          "อื่นๆ",
        ],
      },
      {
        id: "09",
        label: "",
        type: "checkbox",
        question: "ท่านสะดวกฝึกอบรม ช่วงเวลาใด ",
        choices: ["จันทร์ - ศุกร์", "เสาร์ - อาทิตย์", "ทุกช่วงเวลา"],
      },
      {
        id: "09",
        label: "",
        type: "radio",
        question: "ท่านสะดวกฝึกอบรม ช่วงเวลาใด ",
        choices: [
          "ณ สถาบันพัฒนาฝีมือแรงงาน",
          "ณ สถานประกอบการ/บริษัทของท่าน",
          "Online Training",
        ],
      },
      {
        id: "09",
        label: "",
        type: "checkbox",
        question: "ท่านต้องการให้หลักสูตรฝึกอบรมมีการประเมินผลอย่างไร?",
        choices: [
          "การทดสอบหลังการฝึกอบรม",
          "การประเมินผลจากผู้เข้าร่วม",
          "การประเมินผลจากผู้สอน",
          "ไม่มีการประเมินผล",
        ],
      },
      {
        id: "09",
        label: "",
        type: "radio",
        question: "ท่านต้องการให้หลักสูตรมีใบรับรองหรือประกาศนียบัตรหรือไม่?",
        choices: ["จำเป็น", "ไม่จำเป็น"],
      },
    ],
  },
  {
    id: "q10",
    question: "Sales (ฝ่ายขาย)",
    sub_question: [
      {
        id: "10",
        label: "โปรดบอกความต้องการพัฒนาทักษะฝีมือของฝ่ายงานในองค์กรของท่าน",
        type: "radio",
        question: "Sales (ฝ่ายขาย)",
        choices: ["มาก", "ปานกลาง", "น้อย"],
      },
      {
        id: "10",
        label: "ทักษะฝีมือใดที่พนักงานของท่านมี (เลือกได้มากกว่า 1 ข้อ)",
        type: "checkbox",
        question: "Sales (ฝ่ายขาย)",
        choices: [
          "การขายและการนำเสนอผลิตภัณฑ์ IT",
          "การใช้ CRM (Salesforce, HubSpot)",
          "การวิเคราะห์ตลาดและพฤติกรรมลูกค้า",
          "ไม่ทราบ",
        ],
      },
      {
        id: "10",
        label:
          "ทักษะฝีมือด้านใดบ้างที่ท่านต้องการให้พนักงานพัฒนาอย่างต่อเนื่องหรือยังขาดแคลนบุคลากรที่มีทักษะเหล่านี้",
        type: "checkbox",
        question: "Sales (ฝ่ายขาย)",
        choices: [
          "Data-Driven Sales & CRM Management",
          "B2B Sales & Solution Selling",
          "Digital Marketing & Social Selling",
          "ไม่ทราบทักษะที่ควรพัฒนา",
          "ไม่ต้องการพัฒนาทักษะสำหรับฝ่ายนี้",
        ],
      },
      {
        id: "10",
        label: "",
        type: "radio",
        question:
          "ท่านคิดว่าทักษะ Soft Skills มีผลต่อประสิทธิภาพการทำงานของพนักงานภายในองค์กรของท่าน มากน้อยเพียงใด?",
        choices: ["มาก", "ปานกลาง", "น้อย"],
      },
      {
        id: "10",
        label: "",
        type: "checkbox",
        question:
          "ทักษะ Soft Skills ใดที่พนักงานของท่านควรได้รับการพัฒนาเพิ่มเติม? (เลือกได้มากกว่า 1 ข้อ)",
        choices: [
          "การสื่อสารและการนำเสนอ (Communication & Presentation)",
          "การทำงานเป็นทีมและการประสานงาน (Teamwork & Collaboration)",
          "การคิดเชิงวิเคราะห์และการแก้ปัญหา (Critical Thinking & Problem Solving)",
          "ความคิดสร้างสรรค์และนวัตกรรม (Creativity & Innovation)",
          "ภาวะผู้นำและการบริหารทีม (Leadership & Management)",
          "การบริหารเวลาและการทำงานอย่างมีประสิทธิภาพ (Time Management & Productivity)",
          "การปรับตัวต่อการเปลี่ยนแปลง (Adaptability & Resilience)",
          "การรับมือกับความเครียดและความกดดัน Resilience & Stress Management",
          "การเจรจาต่อรองและแก้ไขความขัดแย้ง Negotiation & Conflict Resolution",
          "อื่นๆ",
        ],
      },
      {
        id: "10",
        label: "",
        type: "checkbox",
        question: "ท่านสะดวกฝึกอบรม ช่วงเวลาใด ",
        choices: ["จันทร์ - ศุกร์", "เสาร์ - อาทิตย์", "ทุกช่วงเวลา"],
      },
      {
        id: "10",
        label: "",
        type: "radio",
        question: "ท่านสะดวกฝึกอบรม ช่วงเวลาใด ",
        choices: [
          "ณ สถาบันพัฒนาฝีมือแรงงาน",
          "ณ สถานประกอบการ/บริษัทของท่าน",
          "Online Training",
        ],
      },
      {
        id: "10",
        label: "",
        type: "checkbox",
        question: "ท่านต้องการให้หลักสูตรฝึกอบรมมีการประเมินผลอย่างไร?",
        choices: [
          "การทดสอบหลังการฝึกอบรม",
          "การประเมินผลจากผู้เข้าร่วม",
          "การประเมินผลจากผู้สอน",
          "ไม่มีการประเมินผล",
        ],
      },
      {
        id: "10",
        label: "",
        type: "radio",
        question: "ท่านต้องการให้หลักสูตรมีใบรับรองหรือประกาศนียบัตรหรือไม่?",
        choices: ["จำเป็น", "ไม่จำเป็น"],
      },
    ],
  },

];
